{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a4539911",
   "metadata": {},
   "source": [
    "### AARRR(Referral)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6c170592",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "- 불러온 문서: centrum_review.txt  총 102 단어\n"
     ]
    }
   ],
   "source": [
    "from konlpy.tag import Kkma\n",
    "\n",
    "line_list = []\n",
    "f = open(\"centrum_review.txt\", encoding='utf-8')\n",
    "for line in f:\n",
    "    line = kkma.nouns(line)\n",
    "    line_list.append(line)\n",
    "f.close()\n",
    "\n",
    "print(\"- 불러온 문서: {} \".format(f.name), \"총\",len(line_list), \"단어\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "5a5bfe50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "102\n"
     ]
    }
   ],
   "source": [
    "print(len(line_list))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "ea6f6c5f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[[],\n",
       " ['일반', '약국', '약', '신중', '선택', '겠죠', '부부', '기운', '감사'],\n",
       " ['배송', '물건', '정확'],\n",
       " ['2', '2번째구매', '번째', '구매', '만족'],\n",
       " ['먹습', 'ㄱ', 'ㄱㆍ', 'ㆍ'],\n",
       " ['적극', '적극추천', '추천', '배송'],\n",
       " [],\n",
       " ['부모님', '부모님선물', '선물', '온라인', '온라인최저가', '최저가', '흡족'],\n",
       " ['배송', '책', '비타민', '먹자', '생각', '기분', '탓', '피곤', '듯', '다음', '이용'],\n",
       " ['다', '구', '구매평', '매', '평', '유명', '증명', '제약', '제약회사', '회사', '제품', '수'],\n",
       " ['플라스틱', '포장', '과대', '과대포장', '상품', '상품자체', '자체', '투명'],\n",
       " ['부모님', '피곤', '피곤하다', '하다', '얼마안됬지', '효과'],\n",
       " ['건강',\n",
       "  '구매',\n",
       "  '센트',\n",
       "  '센트룸',\n",
       "  '룸',\n",
       "  '포',\n",
       "  '포맨',\n",
       "  '맨',\n",
       "  '군',\n",
       "  '군대간',\n",
       "  '대간',\n",
       "  '아들',\n",
       "  '가격',\n",
       "  '용'],\n",
       " ['안전', '감사'],\n",
       " ['며칠', '복용', '아침', '피곤'],\n",
       " ['배송', '영양소', '비타민'],\n",
       " ['상품', '감사'],\n",
       " ['번째', '구매', '양도', '배송'],\n",
       " ['배송'],\n",
       " ['침', 'ㅎ', 'ㅎㅅㅎ', 'ㅅ'],\n",
       " ['만족'],\n",
       " [],\n",
       " ['바', '러', '러ㅣ', 'ㅣ'],\n",
       " [],\n",
       " ['거'],\n",
       " ['배송', '배송감사', '감사'],\n",
       " ['만족'],\n",
       " [],\n",
       " [],\n",
       " [],\n",
       " [],\n",
       " ['받앗어'],\n",
       " ['만족'],\n",
       " ['배송'],\n",
       " [],\n",
       " ['만족'],\n",
       " ['구매', '하', '후', '후후', '후히히히', '히', '호', '햐햐햐', '후호', '호'],\n",
       " ['비타민', '연', '하루', '하루섭취기준', '섭취', '기준', '영양소', '소변', '배출', '노란색'],\n",
       " [],\n",
       " ['비타민', '학', '학창시절', '창', '시절', '거랑', '홓', '팅'],\n",
       " ['배송'],\n",
       " ['매해', '맨'],\n",
       " ['배송', '남편', '구매', '구매햏', '햏', '데', '효과', '듯'],\n",
       " [],\n",
       " ['남편', 'ㅂ', '민', '양도', '사야겟어', '배송', '느렷어'],\n",
       " ['남', '거', '포장'],\n",
       " ['센트', '센트룸', '룸', '오랫동안', '먹어봐야겠네'],\n",
       " ['용량', '가격', '비타민', '추천'],\n",
       " ['비타민', '처음', '추천'],\n",
       " ['모르게ㅛ네'],\n",
       " ['다음', '이용', '적극', '적극추천', '추천', '사', '사업', '업', '번창', '멀티', '멀티비타민', '비타민'],\n",
       " ['배송', '포장'],\n",
       " ['배', '배송도', '송도'],\n",
       " ['주문', '지', '6', '6일만', '일', '만'],\n",
       " ['어제', '시작', '나중', '주문', '때', '이용', '수고'],\n",
       " ['배송', '만족'],\n",
       " ['번창'],\n",
       " ['배송', '만족'],\n",
       " ['배송', '감사'],\n",
       " ['ㅉ', 'ㅉㅈㅇ', 'ㅈ', 'ㅇ', '건강', '50', '50자', '자', '감사'],\n",
       " ['건강', '짐', '구라'],\n",
       " ['만족'],\n",
       " ['제품'],\n",
       " ['아빠', '배송', '뾱뾱이없', '비닐', '비닐포장지', '포장지', '당황'],\n",
       " ['거'],\n",
       " ['가격', '가격대비', '대비', '만족'],\n",
       " ['몸', '건강'],\n",
       " ['만족'],\n",
       " ['복용'],\n",
       " ['평소', '센트', '센트룸', '룸', '가격', '구매'],\n",
       " [],\n",
       " ['고등학생',\n",
       "  '아들',\n",
       "  '아빠',\n",
       "  '칼슘',\n",
       "  '칼슘성분',\n",
       "  '성분',\n",
       "  '거',\n",
       "  '일',\n",
       "  '안',\n",
       "  '활력',\n",
       "  '기분',\n",
       "  '기분탓',\n",
       "  '탓',\n",
       "  '건강해질랍니'],\n",
       " [],\n",
       " ['배송'],\n",
       " ['배송'],\n",
       " ['도착', '감사'],\n",
       " [],\n",
       " ['신랑', '감사'],\n",
       " ['배송'],\n",
       " ['배송'],\n",
       " ['적극', '추천'],\n",
       " ['먹어보겠숩니'],\n",
       " [],\n",
       " ['여', '여여퍄패패', '퍄', '패패', 'ㅠ'],\n",
       " ['도착'],\n",
       " ['번째', '번째구매', '구매'],\n",
       " ['만족', '효과', '보이', '보이진', '진', '컨디션', '거'],\n",
       " ['거'],\n",
       " ['배송'],\n",
       " [],\n",
       " ['선물'],\n",
       " ['만족'],\n",
       " ['노어챂ㅊㅌ'],\n",
       " ['만족'],\n",
       " ['만족'],\n",
       " [],\n",
       " [],\n",
       " ['ㄹ'],\n",
       " ['감사'],\n",
       " ['만족'],\n",
       " ['제품'],\n",
       " []]"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "line_list[:]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "27ca2e87",
   "metadata": {},
   "source": [
    "### 불용어 사전 만들기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "9ac7d195",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1/102\r",
      "2/102\r",
      "일반\n",
      "split됨: 일반\n",
      "약국\n",
      "split됨: 약국\n",
      "약\n",
      "신중\n",
      "split됨: 신중\n",
      "선택\n",
      "split됨: 선택\n",
      "겠죠\n",
      "split됨: 겠죠\n",
      "부부\n",
      "split됨: 부부\n",
      "기운\n",
      "split됨: 기운\n",
      "감사\n",
      "split됨: 감사\n",
      "3/102\r",
      "배송\n",
      "split됨: 배송\n",
      "물건\n",
      "split됨: 물건\n",
      "정확\n",
      "split됨: 정확\n",
      "4/102\r",
      "2\n",
      "2번째구매\n",
      "split됨: 2번째구매\n",
      "번째\n",
      "split됨: 번째\n",
      "구매\n",
      "split됨: 구매\n",
      "만족\n",
      "split됨: 만족\n",
      "5/102\r",
      "먹습\n",
      "split됨: 먹습\n",
      "ㄱ\n",
      "ㄱㆍ\n",
      "split됨: ㄱㆍ\n",
      "ㆍ\n",
      "6/102\r",
      "적극\n",
      "split됨: 적극\n",
      "적극추천\n",
      "split됨: 적극추천\n",
      "추천\n",
      "split됨: 추천\n",
      "배송\n",
      "split됨: 배송\n",
      "7/102\r",
      "8/102\r",
      "부모님\n",
      "split됨: 부모님\n",
      "부모님선물\n",
      "split됨: 부모님선물\n",
      "선물\n",
      "split됨: 선물\n",
      "온라인\n",
      "split됨: 온라인\n",
      "온라인최저가\n",
      "split됨: 온라인최저가\n",
      "최저가\n",
      "split됨: 최저가\n",
      "흡족\n",
      "split됨: 흡족\n",
      "9/102\r",
      "배송\n",
      "split됨: 배송\n",
      "책\n",
      "비타민\n",
      "split됨: 비타민\n",
      "먹자\n",
      "split됨: 먹자\n",
      "생각\n",
      "split됨: 생각\n",
      "기분\n",
      "split됨: 기분\n",
      "탓\n",
      "피곤\n",
      "split됨: 피곤\n",
      "듯\n",
      "다음\n",
      "split됨: 다음\n",
      "이용\n",
      "split됨: 이용\n",
      "10/102\r",
      "다\n",
      "구\n",
      "구매평\n",
      "split됨: 구매평\n",
      "매\n",
      "평\n",
      "유명\n",
      "split됨: 유명\n",
      "증명\n",
      "split됨: 증명\n",
      "제약\n",
      "split됨: 제약\n",
      "제약회사\n",
      "split됨: 제약회사\n",
      "회사\n",
      "split됨: 회사\n",
      "제품\n",
      "split됨: 제품\n",
      "수\n",
      "11/102\r",
      "플라스틱\n",
      "split됨: 플라스틱\n",
      "포장\n",
      "split됨: 포장\n",
      "과대\n",
      "split됨: 과대\n",
      "과대포장\n",
      "split됨: 과대포장\n",
      "상품\n",
      "split됨: 상품\n",
      "상품자체\n",
      "split됨: 상품자체\n",
      "자체\n",
      "split됨: 자체\n",
      "투명\n",
      "split됨: 투명\n",
      "12/102\r",
      "부모님\n",
      "split됨: 부모님\n",
      "피곤\n",
      "split됨: 피곤\n",
      "피곤하다\n",
      "split됨: 피곤하다\n",
      "하다\n",
      "split됨: 하다\n",
      "얼마안됬지\n",
      "split됨: 얼마안됬지\n",
      "효과\n",
      "split됨: 효과\n",
      "13/102\r",
      "건강\n",
      "split됨: 건강\n",
      "구매\n",
      "split됨: 구매\n",
      "센트\n",
      "split됨: 센트\n",
      "센트룸\n",
      "split됨: 센트룸\n",
      "룸\n",
      "포\n",
      "포맨\n",
      "split됨: 포맨\n",
      "맨\n",
      "군\n",
      "군대간\n",
      "split됨: 군대간\n",
      "대간\n",
      "split됨: 대간\n",
      "아들\n",
      "split됨: 아들\n",
      "가격\n",
      "split됨: 가격\n",
      "용\n",
      "14/102\r",
      "안전\n",
      "split됨: 안전\n",
      "감사\n",
      "split됨: 감사\n",
      "15/102\r",
      "며칠\n",
      "split됨: 며칠\n",
      "복용\n",
      "split됨: 복용\n",
      "아침\n",
      "split됨: 아침\n",
      "피곤\n",
      "split됨: 피곤\n",
      "16/102\r",
      "배송\n",
      "split됨: 배송\n",
      "영양소\n",
      "split됨: 영양소\n",
      "비타민\n",
      "split됨: 비타민\n",
      "17/102\r",
      "상품\n",
      "split됨: 상품\n",
      "감사\n",
      "split됨: 감사\n",
      "18/102\r",
      "번째\n",
      "split됨: 번째\n",
      "구매\n",
      "split됨: 구매\n",
      "양도\n",
      "split됨: 양도\n",
      "배송\n",
      "split됨: 배송\n",
      "19/102\r",
      "배송\n",
      "split됨: 배송\n",
      "20/102\r",
      "침\n",
      "ㅎ\n",
      "ㅎㅅㅎ\n",
      "split됨: ㅎㅅㅎ\n",
      "ㅅ\n",
      "21/102\r",
      "만족\n",
      "split됨: 만족\n",
      "22/102\r",
      "23/102\r",
      "바\n",
      "러\n",
      "러ㅣ\n",
      "split됨: 러ㅣ\n",
      "ㅣ\n",
      "24/102\r",
      "25/102\r",
      "거\n",
      "26/102\r",
      "배송\n",
      "split됨: 배송\n",
      "배송감사\n",
      "split됨: 배송감사\n",
      "감사\n",
      "split됨: 감사\n",
      "27/102\r",
      "만족\n",
      "split됨: 만족\n",
      "28/102\r",
      "29/102\r",
      "30/102\r",
      "31/102\r",
      "32/102\r",
      "받앗어\n",
      "split됨: 받앗어\n",
      "33/102\r",
      "만족\n",
      "split됨: 만족\n",
      "34/102\r",
      "배송\n",
      "split됨: 배송\n",
      "35/102\r",
      "36/102\r",
      "만족\n",
      "split됨: 만족\n",
      "37/102\r",
      "구매\n",
      "split됨: 구매\n",
      "하\n",
      "후\n",
      "후후\n",
      "split됨: 후후\n",
      "후히히히\n",
      "split됨: 후히히히\n",
      "히\n",
      "호\n",
      "햐햐햐\n",
      "split됨: 햐햐햐\n",
      "후호\n",
      "split됨: 후호\n",
      "호\n",
      "38/102\r",
      "비타민\n",
      "split됨: 비타민\n",
      "연\n",
      "하루\n",
      "split됨: 하루\n",
      "하루섭취기준\n",
      "split됨: 하루섭취기준\n",
      "섭취\n",
      "split됨: 섭취\n",
      "기준\n",
      "split됨: 기준\n",
      "영양소\n",
      "split됨: 영양소\n",
      "소변\n",
      "split됨: 소변\n",
      "배출\n",
      "split됨: 배출\n",
      "노란색\n",
      "split됨: 노란색\n",
      "39/102\r",
      "40/102\r",
      "비타민\n",
      "split됨: 비타민\n",
      "학\n",
      "학창시절\n",
      "split됨: 학창시절\n",
      "창\n",
      "시절\n",
      "split됨: 시절\n",
      "거랑\n",
      "split됨: 거랑\n",
      "홓\n",
      "팅\n",
      "41/102\r",
      "배송\n",
      "split됨: 배송\n",
      "42/102\r",
      "매해\n",
      "split됨: 매해\n",
      "맨\n",
      "43/102\r",
      "배송\n",
      "split됨: 배송\n",
      "남편\n",
      "split됨: 남편\n",
      "구매\n",
      "split됨: 구매\n",
      "구매햏\n",
      "split됨: 구매햏\n",
      "햏\n",
      "데\n",
      "효과\n",
      "split됨: 효과\n",
      "듯\n",
      "44/102\r",
      "45/102\r",
      "남편\n",
      "split됨: 남편\n",
      "ㅂ\n",
      "민\n",
      "양도\n",
      "split됨: 양도\n",
      "사야겟어\n",
      "split됨: 사야겟어\n",
      "배송\n",
      "split됨: 배송\n",
      "느렷어\n",
      "split됨: 느렷어\n",
      "46/102\r",
      "남\n",
      "거\n",
      "포장\n",
      "split됨: 포장\n",
      "47/102\r",
      "센트\n",
      "split됨: 센트\n",
      "센트룸\n",
      "split됨: 센트룸\n",
      "룸\n",
      "오랫동안\n",
      "split됨: 오랫동안\n",
      "먹어봐야겠네\n",
      "split됨: 먹어봐야겠네\n",
      "48/102\r",
      "용량\n",
      "split됨: 용량\n",
      "가격\n",
      "split됨: 가격\n",
      "비타민\n",
      "split됨: 비타민\n",
      "추천\n",
      "split됨: 추천\n",
      "49/102\r",
      "비타민\n",
      "split됨: 비타민\n",
      "처음\n",
      "split됨: 처음\n",
      "추천\n",
      "split됨: 추천\n",
      "50/102\r",
      "모르게ㅛ네\n",
      "split됨: 모르게ㅛ네\n",
      "51/102\r",
      "다음\n",
      "split됨: 다음\n",
      "이용\n",
      "split됨: 이용\n",
      "적극\n",
      "split됨: 적극\n",
      "적극추천\n",
      "split됨: 적극추천\n",
      "추천\n",
      "split됨: 추천\n",
      "사\n",
      "사업\n",
      "split됨: 사업\n",
      "업\n",
      "번창\n",
      "split됨: 번창\n",
      "멀티\n",
      "split됨: 멀티\n",
      "멀티비타민\n",
      "split됨: 멀티비타민\n",
      "비타민\n",
      "split됨: 비타민\n",
      "52/102\r",
      "배송\n",
      "split됨: 배송\n",
      "포장\n",
      "split됨: 포장\n",
      "53/102\r",
      "배\n",
      "배송도\n",
      "split됨: 배송도\n",
      "송도\n",
      "split됨: 송도\n",
      "54/102\r",
      "주문\n",
      "split됨: 주문\n",
      "지\n",
      "6\n",
      "6일만\n",
      "split됨: 6일만\n",
      "일\n",
      "만\n",
      "55/102\r",
      "어제\n",
      "split됨: 어제\n",
      "시작\n",
      "split됨: 시작\n",
      "나중\n",
      "split됨: 나중\n",
      "주문\n",
      "split됨: 주문\n",
      "때\n",
      "이용\n",
      "split됨: 이용\n",
      "수고\n",
      "split됨: 수고\n",
      "56/102\r",
      "배송\n",
      "split됨: 배송\n",
      "만족\n",
      "split됨: 만족\n",
      "57/102\r",
      "번창\n",
      "split됨: 번창\n",
      "58/102\r",
      "배송\n",
      "split됨: 배송\n",
      "만족\n",
      "split됨: 만족\n",
      "59/102\r",
      "배송\n",
      "split됨: 배송\n",
      "감사\n",
      "split됨: 감사\n",
      "60/102\r",
      "ㅉ\n",
      "ㅉㅈㅇ\n",
      "split됨: ㅉㅈㅇ\n",
      "ㅈ\n",
      "ㅇ\n",
      "건강\n",
      "split됨: 건강\n",
      "50\n",
      "split됨: 50\n",
      "50자\n",
      "split됨: 50자\n",
      "자\n",
      "감사\n",
      "split됨: 감사\n",
      "61/102\r",
      "건강\n",
      "split됨: 건강\n",
      "짐\n",
      "구라\n",
      "split됨: 구라\n",
      "62/102\r",
      "만족\n",
      "split됨: 만족\n",
      "63/102\r",
      "제품\n",
      "split됨: 제품\n",
      "64/102\r",
      "아빠\n",
      "split됨: 아빠\n",
      "배송\n",
      "split됨: 배송\n",
      "뾱뾱이없\n",
      "split됨: 뾱뾱이없\n",
      "비닐\n",
      "split됨: 비닐\n",
      "비닐포장지\n",
      "split됨: 비닐포장지\n",
      "포장지\n",
      "split됨: 포장지\n",
      "당황\n",
      "split됨: 당황\n",
      "65/102\r",
      "거\n",
      "66/102\r",
      "가격\n",
      "split됨: 가격\n",
      "가격대비\n",
      "split됨: 가격대비\n",
      "대비\n",
      "split됨: 대비\n",
      "만족\n",
      "split됨: 만족\n",
      "67/102\r",
      "몸\n",
      "건강\n",
      "split됨: 건강\n",
      "68/102\r",
      "만족\n",
      "split됨: 만족\n",
      "69/102\r",
      "복용\n",
      "split됨: 복용\n",
      "70/102\r",
      "평소\n",
      "split됨: 평소\n",
      "센트\n",
      "split됨: 센트\n",
      "센트룸\n",
      "split됨: 센트룸\n",
      "룸\n",
      "가격\n",
      "split됨: 가격\n",
      "구매\n",
      "split됨: 구매\n",
      "71/102\r",
      "72/102\r",
      "고등학생\n",
      "split됨: 고등학생\n",
      "아들\n",
      "split됨: 아들\n",
      "아빠\n",
      "split됨: 아빠\n",
      "칼슘\n",
      "split됨: 칼슘\n",
      "칼슘성분\n",
      "split됨: 칼슘성분\n",
      "성분\n",
      "split됨: 성분\n",
      "거\n",
      "일\n",
      "안\n",
      "활력\n",
      "split됨: 활력\n",
      "기분\n",
      "split됨: 기분\n",
      "기분탓\n",
      "split됨: 기분탓\n",
      "탓\n",
      "건강해질랍니\n",
      "split됨: 건강해질랍니\n",
      "73/102\r",
      "74/102\r",
      "배송\n",
      "split됨: 배송\n",
      "75/102\r",
      "배송\n",
      "split됨: 배송\n",
      "76/102\r",
      "도착\n",
      "split됨: 도착\n",
      "감사\n",
      "split됨: 감사\n",
      "77/102\r",
      "78/102\r",
      "신랑\n",
      "split됨: 신랑\n",
      "감사\n",
      "split됨: 감사\n",
      "79/102\r",
      "배송\n",
      "split됨: 배송\n",
      "80/102\r",
      "배송\n",
      "split됨: 배송\n",
      "81/102\r",
      "적극\n",
      "split됨: 적극\n",
      "추천\n",
      "split됨: 추천\n",
      "82/102\r",
      "먹어보겠숩니\n",
      "split됨: 먹어보겠숩니\n",
      "83/102\r",
      "84/102\r",
      "여\n",
      "여여퍄패패\n",
      "split됨: 여여퍄패패\n",
      "퍄\n",
      "패패\n",
      "split됨: 패패\n",
      "ㅠ\n",
      "85/102\r",
      "도착\n",
      "split됨: 도착\n",
      "86/102\r",
      "번째\n",
      "split됨: 번째\n",
      "번째구매\n",
      "split됨: 번째구매\n",
      "구매\n",
      "split됨: 구매\n",
      "87/102\r",
      "만족\n",
      "split됨: 만족\n",
      "효과\n",
      "split됨: 효과\n",
      "보이\n",
      "split됨: 보이\n",
      "보이진\n",
      "split됨: 보이진\n",
      "진\n",
      "컨디션\n",
      "split됨: 컨디션\n",
      "거\n",
      "88/102\r",
      "거\n",
      "89/102\r",
      "배송\n",
      "split됨: 배송\n",
      "90/102\r",
      "91/102\r",
      "선물\n",
      "split됨: 선물\n",
      "92/102\r",
      "만족\n",
      "split됨: 만족\n",
      "93/102\r",
      "노어챂ㅊㅌ\n",
      "split됨: 노어챂ㅊㅌ\n",
      "94/102\r",
      "만족\n",
      "split됨: 만족\n",
      "95/102\r",
      "만족\n",
      "split됨: 만족\n",
      "96/102\r",
      "97/102\r",
      "98/102\r",
      "ㄹ\n",
      "99/102\r",
      "감사\n",
      "split됨: 감사\n",
      "100/102\r",
      "만족\n",
      "split됨: 만족\n",
      "101/102\r",
      "제품\n",
      "split됨: 제품\n",
      "102/102\r"
     ]
    }
   ],
   "source": [
    "word_frequency = {}\n",
    "noun_list = []\n",
    "\n",
    "#불용어 리스트\n",
    "stop_list = []\n",
    "line_number = 0\n",
    "\n",
    "for line in line_list[:]:\n",
    "    line_number += 1\n",
    "    print(str(line_number) + \"/\" + str(len(line_list)), end=\"\\r\")\n",
    "    noun = []\n",
    "    for word in line:\n",
    "        print(word)\n",
    "        if word.split(\"/\")[0] not in stop_list and len(word.split(\"/\")[0]) > 1:\n",
    "            print(\"split됨:\", word)\n",
    "            noun.append(word.split(\"/\")[0])\n",
    "#             print(noun)\n",
    "            if word not in word_frequency.keys():\n",
    "#                 print(word)\n",
    "                word_frequency[word] = 1\n",
    "#                 print(word_frequency)\n",
    "            else:\n",
    "                word_frequency[word] += 1\n",
    "    noun_list.extend(noun)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "6b2a3bab",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'일반/102'"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "a = '일반/102'\n",
    "a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "d7d26709",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'일반'"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "a.split('/')[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43e4df31",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3b09ee95",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d594ae0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44cb18ed",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54fd1919",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f57369bf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5232d9c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
